### PR TITLE
updated serverside to clientside

### PR DESCRIPTION
**Pull request by mohzys23**

### CODE REVIEW

**Comment by wskish** [comment]
i am starting to test this but run into an issue with docker builder in your client_rendering branch:

make TAG=jul13
docker buildx build --platform linux/amd64,linux/arm64 --push -t jiggyai/chatbot-ui:jul13 .
[+] Building 46.0s (15/25)                                                                                                                                                                     
 => [internal] load build definition from Dockerfile                                                                                                                                      0.0s
 => => transferring dockerfile: 783B                                                                                                                                                      0.0s
 => [internal] load .dockerignore                                                                                                                                                         0.0s
 => => transferring context: 82B                                                                                                                                                          0.0s
 => [linux/arm64 internal] load metadata for docker.io/library/node:19-alpine                                                                                                             0.5s
 => [linux/amd64 internal] load metadata for docker.io/library/node:19-alpine                                                                                                             0.5s
 => [linux/arm64 production 1/8] FROM docker.io/library/node:19-alpine@sha256:8ec543d4795e2e85af924a24f8acb039792ae9fe8a42ad5b4bf4c277ab34b62e                                            0.0s
 => => resolve docker.io/library/node:19-alpine@sha256:8ec543d4795e2e85af924a24f8acb039792ae9fe8a42ad5b4bf4c277ab34b62e                                                                   0.0s
 => [internal] load build context                                                                                                                                                         0.1s
 => => transferring context: 628.98kB                                                                                                                                                     0.0s
 => [linux/amd64 production 1/8] FROM docker.io/library/node:19-alpine@sha256:8ec543d4795e2e85af924a24f8acb039792ae9fe8a42ad5b4bf4c277ab34b62e                                            0.0s
 => => resolve docker.io/library/node:19-alpine@sha256:8ec543d4795e2e85af924a24f8acb039792ae9fe8a42ad5b4bf4c277ab34b62e                                                                   0.0s
 => CACHED [linux/amd64 production 2/8] WORKDIR /app                                                                                                                                      0.0s
 => [linux/amd64 base 3/3] COPY package*.json ./                                                                                                                                          0.0s
 => [linux/amd64 dependencies 1/1] RUN npm ci                                                                                                                                            31.5s
 => [linux/amd64 build 1/2] COPY . .                                                                                                                                                      0.3s
 => ERROR [linux/amd64 build 2/2] RUN npm run build                                                                                                                                      13.4s 
 => CACHED [linux/arm64 production 2/8] WORKDIR /app                                                                                                                                      0.0s 
 => [linux/arm64 production 3/8] COPY --from=dependencies /app/node_modules ./node_modules                                                                                               10.5s 
 => [linux/amd64 production 3/8] COPY --from=dependencies /app/node_modules ./node_modules                                                                                               10.4s 
------                                                                                                                                                                                         
 > [linux/amd64 build 2/2] RUN npm run build:                                                                                                                                                  
#0 0.576                                                                                                                                                                                       
#0 0.576 > ai-chatbot-starter@0.1.0 build                                                                                                                                                      
#0 0.576 > next build                                                                                                                                                                          
#0 0.576                                                                                                                                                                                       
#0 1.167 Attention: Next.js now collects completely anonymous telemetry regarding usage.
#0 1.168 This information is used to shape Next.js' roadmap and prioritize features.
#0 1.168 You can learn more, including how to opt-out if you'd not like to participate in this anonymous program, by visiting the following URL:
#0 1.168 https://nextjs.org/telemetry
#0 1.168 
#0 1.324 info  - Linting and checking validity of types...
#0 4.455 
#0 4.455 ./pages/api/home/home.tsx
#0 4.455 81:6  Warning: React Hook useEffect has a missing dependency: 'getToken'. Either include it or remove the dependency array.  react-hooks/exhaustive-deps
#0 4.455 377:6  Warning: React Hook useEffect has missing dependencies: 'conversations', 'models', and 't'. Either include them or remove the dependency array.  react-hooks/exhaustive-deps
#0 4.455 397:6  Warning: React Hook useEffect has a missing dependency: 'dispatch'. Either include it or remove the dependency array.  react-hooks/exhaustive-deps
#0 4.455 
#0 4.455 ./components/Chat/Chat.tsx
#0 4.455 254:5  Warning: React Hook useCallback has a missing dependency: 'homeDispatch'. Either include it or remove the dependency array.  react-hooks/exhaustive-deps
#0 4.455 411:6  Warning: React Hook useEffect has missing dependencies: 'assistantMessage', 'conversations', and 'homeDispatch'. Either include them or remove the dependency array.  react-hooks/exhaustive-deps
#0 4.455 
#0 4.455 ./components/Chat/ChatInput.tsx
#0 4.455 240:6  Warning: React Hook useEffect has a missing dependency: 'textareaRef'. Either include it or remove the dependency array.  react-hooks/exhaustive-deps
#0 4.455 
#0 4.455 ./components/Chat/ChatLoader.tsx
#0 4.455 16:11  Warning: Using `` could result in slower LCP and higher bandwidth. Consider using `<Image />` from `next/image` to automatically optimize images. This may incur additional usage or cost from your provider. See: https://nextjs.org/docs/messages/no-img-element  @next/next/no-img-element
#0 4.455 
#0 4.455 ./components/Chat/ChatMessage.tsx
#0 4.455 140:13  Warning: Using `` could result in slower LCP and higher bandwidth. Consider using `<Image />` from `next/image` to automatically optimize images. This may incur additional usage or cost from your provider. See: https://nextjs.org/docs/messages/no-img-element  @next/next/no-img-element
#0 4.455 
#0 4.455 ./components/Chatbar/Chatbar.tsx
#0 4.455 204:6  Warning: React Hook useEffect has a missing dependency: 'chatDispatch'. Either include it or remove the dependency array.  react-hooks/exhaustive-deps
#0 4.455 
#0 4.455 ./components/Promptbar/Promptbar.tsx
#0 4.455 115:6  Warning: React Hook useEffect has a missing dependency: 'promptDispatch'. Either include it or remove the dependency array.  react-hooks/exhaustive-deps
#0 4.455 
#0 4.455 info  - Need to disable some ESLint rules? Learn more here: https://nextjs.org/docs/basic-features/eslint#disabling-rules
#0 9.955 Failed to compile.
#0 9.955 
#0 9.955 ./pages/api/home/index.ts:1:19
#0 9.955 Type error: Module '"./home"' has no exported member 'getServerSideProps'. Did you mean to use 'import getServerSideProps from "./home"' instead?
#0 9.955 
#0 9.955 > 1 | export { default, getServerSideProps } from './home';
#0 9.955     |                   ^
#0 9.955   2 | 
------
Dockerfile:14
--------------------
  12 |     FROM dependencies AS build
  13 |     COPY . .
  14 | >>> RUN npm run build
  15 |     
  16 |     # ---- Production ----
--------------------
ERROR: failed to solve: process "/bin/sh -c npm run build" did not complete successfully: exit code: 1
make: *** [build] Error 1

**Comment by amy-why** [comment]
yeah, for me I always have to run two steps:
docker buildx create --use

then
docker buildx build --platform linux/amd64,linux/arm64 --push -t jiggyai/chatbot-ui:amy713 .

does that work for you?

**Comment by wskish** [comment]
i did the "docker buildx create --use" first but then with either of those build commands get the error above.

**Comment by amy-why** [comment]
I am out in a conference. How about going back to old makefile before my change to support M1 chip. I was able to built last night on my Mac laptop. I need to check on the iMac later.

**Comment by mohzys23** [comment]
I just pushed an update to this PR please @wskish @amy-why verify if the docker build works now.

**Comment by amy-why** [comment]
@mohzys23 I had the right side bar closed and user won't be able to see it or open it. It is visible to in your build.
I can build your code on my mac with apple M2 chip, and I put on chat-staging.jiggy.ai. 
My npm version is 9.6.6.
I'll check build issue on Intel chip later.

**Comment by mohzys23** [comment]
@amy-why The right sidebar works fine locally, but I will install docker right away and try to run the build. 

https://github.com/jiggy-ai/jiggybase-chatbot-ui/assets/39748749/5b8b59d7-e8e3-4b8c-a85f-84478ecf95c0

**Comment by amy-why** [comment]
We won't show user the right side bar, user cannot access it. Please check the production build at chat.jiggy.ai

**Comment by mohzys23** [comment]
@amy-why Okay noted, I have pushed an update to fix hiding the prompt.

**Comment by amy-why** [comment]
worked. I put on staging. Here is my build output as a reference:
```
amy (client_rendering *) jiggybase-chatbot-ui $ docker buildx build --platform linux/amd64,linux/arm64 --push -t jiggyai/chatbot-ui:amy714_v2 .
[+] Building 62.1s (28/28) FINISHED                                                                                                                                                                        
 => [internal] load build definition from Dockerfile                                                                                                                                                  0.0s
 => => transferring dockerfile: 783B                                                                                                                                                                  0.0s
 => [internal] load .dockerignore                                                                                                                                                                     0.0s
 => => transferring context: 82B                                                                                                                                                                      0.0s
 => [linux/arm64 internal] load metadata for docker.io/library/node:19-alpine                                                                                                                         1.9s
 => [linux/amd64 internal] load metadata for docker.io/library/node:19-alpine                                                                                                                         1.4s
 => [auth] library/node:pull token for registry-1.docker.io                                                                                                                                           0.0s
 => [internal] load build context                                                                                                                                                                     4.9s
 => => transferring context: 317.80MB                                                                                                                                                                 4.9s
 => [linux/amd64 production 1/8] FROM docker.io/library/node:19-alpine@sha256:8ec543d4795e2e85af924a24f8acb039792ae9fe8a42ad5b4bf4c277ab34b62e                                                        0.0s
 => => resolve docker.io/library/node:19-alpine@sha256:8ec543d4795e2e85af924a24f8acb039792ae9fe8a42ad5b4bf4c277ab34b62e                                                                               0.0s
 => [linux/arm64 base 1/3] FROM docker.io/library/node:19-alpine@sha256:8ec543d4795e2e85af924a24f8acb039792ae9fe8a42ad5b4bf4c277ab34b62e                                                              0.0s
 => => resolve docker.io/library/node:19-alpine@sha256:8ec543d4795e2e85af924a24f8acb039792ae9fe8a42ad5b4bf4c277ab34b62e                                                                               0.0s
 => CACHED [linux/arm64 base 2/3] WORKDIR /app                                                                                                                                                        0.0s
 => CACHED [linux/arm64 base 3/3] COPY package*.json ./                                                                                                                                               0.0s
 => CACHED [linux/arm64 dependencies 1/1] RUN npm ci                                                                                                                                                  0.0s
 => [linux/arm64 build 1/2] COPY . .                                                                                                                                                                  1.4s
 => [linux/arm64 build 2/2] RUN npm run build                                                                                                                                                        24.4s
 => CACHED [linux/arm64 production 3/8] COPY --from=dependencies /app/node_modules ./node_modules                                                                                                     0.0s 
 => [linux/arm64 production 4/8] COPY --from=build /app/.next ./.next                                                                                                                                 1.1s 
 => CACHED [linux/amd64 production 2/8] WORKDIR /app                                                                                                                                                  0.0s 
 => CACHED [linux/amd64 production 3/8] COPY --from=dependencies /app/node_modules ./node_modules                                                                                                     0.0s 
 => [linux/arm64 production 5/8] COPY --from=build /app/public ./public                                                                                                                               0.1s 
 => [linux/amd64 production 4/8] COPY --from=build /app/.next ./.next                                                                                                                                 1.2s 
 => [linux/arm64 production 6/8] COPY --from=build /app/package*.json ./                                                                                                                              1.2s
 => [linux/amd64 production 5/8] COPY --from=build /app/public ./public                                                                                                                               0.1s
 => [linux/amd64 production 6/8] COPY --from=build /app/package*.json ./                                                                                                                              0.7s
 => [linux/arm64 production 7/8] COPY --from=build /app/next.config.js ./next.config.js                                                                                                               0.0s
 => [linux/arm64 production 8/8] COPY --from=build /app/next-i18next.config.js ./next-i18next.config.js                                                                                               0.0s
 => [linux/amd64 production 7/8] COPY --from=build /app/next.config.js ./next.config.js                                                                                                               0.0s
 => [linux/amd64 production 8/8] COPY --from=build /app/next-i18next.config.js ./next-i18next.config.js                                                                                               0.0s
 => exporting to image                                                                                                                                                                               24.1s
 => => exporting layers                                                                                                                                                                               9.0s
 => => exporting manifest sha256:6c40ae32701912110125b66ac74459980a6a613c1535326f637d259bb8667d2f                                                                                                     0.0s
 => => exporting config sha256:c9fbe6757a7a7818b15a9a282b6b9b4a9ad591cd5609f3e7dcbccca3bbb9742b                                                                                                       0.0s
 => => exporting attestation manifest sha256:303050a37cc99d5c3d973c8f17255ec0ec74d3314d3ec2e22b666285ed345cdd                                                                                         0.0s
 => => exporting manifest sha256:c036e83de8e14dae9e1af1c8c859ec130e087767a335b0383d611cebfe267916                                                                                                     0.0s
 => => exporting config sha256:954a963ff942eeffc0a95e87b121bdd92f07556354940a3196d6a103adaaa9e0                                                                                                       0.0s
 => => exporting attestation manifest sha256:c8074d3731b527e5ac28bcc741d35a0483e47f13ac3b0129d949839146177c61                                                                                         0.0s
 => => exporting manifest list sha256:678b3fa0d62a354ca152d0d6beb626615ebf7c3e5d4c6e90996c697f354911fd                                                                                                0.0s
 => => pushing layers                                                                                                                                                                                13.4s
 => => pushing manifest for docker.io/jiggyai/chatbot-ui:amy714_v2@sha256:678b3fa0d62a354ca152d0d6beb626615ebf7c3e5d4c6e90996c697f354911fd                                                            1.7s
 => [auth] jiggyai/chatbot-ui:pull,push token for registry-1.docker.io
```

**Comment by amy-why** [comment]
it builds for me on Intel base IMac too.

**Pull request merged**
